name: Website
on: [push]
jobs:

  build:
    name: Website
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.60.1'
        extended: true

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build Website
      env:
        SERVER_USER: ${{ secrets.SERVER_USER }}
        SERVER_PATH: ${{ secrets.SERVER_PATH }}
        SERVER_KEY:  ${{ secrets.SERVER_KEY  }}
      run: |
        cd website
        make
        echo $SERVER_KEY > go-under-the-hood.key
        scp -i go-under-the-hood.key -r public/* $SERVER_USER@changkun.de:$SERVER_PATH