name: Website
on: [push]
jobs:

  build:
    name: Website
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.60.1'
        extended: true

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build Website
      env:
        USER: ${{ secrets.SERVER_USER }}
        TARGET: ${{ secrets.SERVER_PATH }}
        KEY: ${{ secrets.SERVER_KEY }}
      run: |
        cd website && make
        echo $KEY > deploy
        chmod 400 deploy
        scp -i ./deploy -r public/* $USER@changkun.de:$TARGET